sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=29e69e7da6b55678f27b7de2444b6161a6c98e3c4b22e0e017ebab87ada18fd5
language: ruby
rvm:
  - 2.2
  - 2.6
gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile
matrix:
  exclude:
    - gemfile: gemfiles/3.2.gemfile
      rvm: 2.6
    - gemfile: gemfiles/4.0.gemfile
      rvm: 2.6
    - gemfile: gemfiles/6.0.gemfile
      rvm: 2.2
before_install:
  - gem i rubygems-update -v '<3' && update_rubygems
  - gem install bundler -v 1.17.3
  - gem --version
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
